### ISSUE TITLE
Heart containers cap not working

### ISSUE THREAD

**Issue by teneburu** [Tictim/Paraglider#101]
Hello

As said in title, the max health cap does not work. It is said on the forge page that by default the cap is 20 hearts. Despite this, on 20.1.1 version, I find myself able to go over the cap. The cap seems to be respected in the Horned Statue, but not the Goddess Statue. I have specified the max health in the paraglider config. This should be easily reproducable. Hoping a fix can be done soon, in the meantime I will track my players and force them to exchange their hearts containers back. Thank you for reading my issue.

**Comment by Tictim** [comment]
The bug is not reproduceable; I think you mistook the config value's meaning.

The 20 cap means you can gain 20 Heart Containers total, and have +20 hearts as result. Thus, the maximum loadout achievable in default config is 30 hearts, or 3 rows of hearts. The Stamina Vessels have 10 cap by default, with sets of behavior and restrictions different to Heart Containers.

This issue will be closed, as the reported issue is likely to be false; please let me know if you have anything else.
