### ISSUE TITLE
[ Feature Request / Question ] Is there a way to hide stamina?

### ISSUE THREAD

**Issue by LunarDev-git** [Tictim/Paraglider#111]
I'm currently working on an updated version of my modpack, This aims to create a cozy and non-overwhelming experience for modded minecraft. 
However, there's an "issue" I'd like to address. When launching a world or entering a game, the stamina icon appears, potentially overwhelming new players with unnecessary information and causing confusion. due to new and strange icons

I'm thinking of two possible solutions:
**A)** Is there a way to prevent the stamina from depleting upon entering a world and instead set it to full automatically?
**B)** Alternatively, is it possible to hide the stamina icon entirely during gameplay?

Thanks

**Comment by Tictim** [comment]
The first suggestion has been implemented in [8af3286](https://github.com/Tictim/Paraglider/commit/8af328696e333ebd903bd8bbf94f4d0dcbb4ae97).

On the second suggestion I am assuming you're talking about ways to disable the stamina system itself, since otherwise it doesn't make any sense. You can achieve that by changing server-side config - either manually editing each stamina delta values, or turning off both `paraglidingConsumesStamina` and `runningConsumesStamina` options.(assuming you don't have any other addon that makes use of stamina system)
