### ISSUE TITLE
Cannot recover stamina underwater.

### ISSUE THREAD

**Issue by sharlin073** [Tictim/Paraglider#15]
It seems like we cannot recover stamina underwater while standing still.

So even when we have conduits or water breathing, underwater exploration might be very limited.

I'm not sure this is a bug, but reporting for just in case.
(Maybe we can have a config option for how fast each action can consume stamina?)

**Comment by Tictim** [comment]
Stamina not regenerating underwater is intended behaviour. It also can be mitigated by number of methods, such as:
* Having Water Breathing potion effect.
* Equipping armor with any level of Aqua Affinity or Depth Strider enchantment.
* Equipping Turtle Shell.

If any of those matches, you will be able to regenerate stamina while in the water. And I think it reduces stamina consumption while swimming underwater but I'm not sure about that part. Maybe stamina regenerates regardless of whether you are swimming or not.

It seems like the only odd part about your report is Water Breathing part. Does it actually drain your stamina even when you have the potion effect? Please check again and let me know. I've never seen or used Conduit ingame(lmao) so I'm not sure about it though, but if it works by providing nearby players temporary water breathing effect, it should work. I'd be surprised if they didn't work like that.

For config part I gave it some thoughts, but it was dropped because there's no real good reason to say 'Hey fellow minecraft players, go balance my mod yourself'. If you think stamina regeneration needs some balancing, tell me what specific action needs to be changed.

**Comment by sharlin073** [comment]
Thank you for the details! I think it is well balanced then.
No, my bad. I did not try with the potion, but just thought "if stamina limits in-water activity this much, then what's the point of water breathing?". I'm sorry that I did not make it clear.

Thanks again!

(Closing the issue!)
