### ISSUE TITLE
Durability on paragliders

### ISSUE THREAD

**Issue by Krampus69** [Tictim/Paraglider#17]
Hello,
First of all : Thank you so much for this mod. It's an awesome and my team and I are planning to include it in our future modpack. I was wondering if there was any way to include some durability to the paragliders via a config file option.

Since we're not using the stamina bar we felt like it was kind of overpowered to just have a paraglider in the inventory with zero downside.
Anyway, thank you again for your work. (I'm sorry I couldn't put a "enhancement" label on this thread, I can't find where to do it)

**Comment by Tictim** [comment]
Adding configurable durability isn't something that I hear about the first time. I think I declined it before. But I see the appeal and it would be fine addition to the mod. I mean, someone wants it, could be made configurable and it's not quantum physics. In fact it would be fairly simple.

And the cosmetic recipes would need some touch, because they need to retain durability and such. I could make the game to copy-paste NBT data of paraglider, but that means I probably will have to define new recipe type. Doing this way will change behavior of recipe, because switching between paraglider skins would preserve color and such, instead of removing it like before. It won't be a problem though, they can always use cauldron to get rid of color.

As this proposal is not about game breaking issues or anything, I kinda want to hold on until 1.3.2.0 drops with full spirit orb features. Part of the reason is 1.3.2.x branch uses datagen while 1.3.1.x branch does not(because I'm an idiot with monkey brain), and I don't want to work on recipes without using datagen 😛

It means the feature will take some time before releasing. Or maybe someone else can port it on 1.3.1.x I could ship it before 1.3.2.x. Maybe. Just maybe. Given the pull request rate of whopping zero PRs per millennia, I expect someone else will definitely work on my mod.
