### ISSUE TITLE
Visual bug when playing with epicfight mod

### ISSUE THREAD

**Issue by buttmanlegface** [Tictim/Paraglider#22]
Hi so there's this bug when playing with epic fight mod that causes the player to look like they're walking on the paraglider mid air.

**Comment by Tictim** [comment]
Of course it won't work because they yeeted out the entire player model system in favor of their own model and animations. Supporting the mod from my endpoint is nigh impossible.

The only hope you've got is the Epic Fight mod themselves adding custom made paragliding animations to their mod. But tbh I don't see that coming. I suggest you to drop this as well.
