### ISSUE TITLE
Config not working as intended on server

### ISSUE THREAD

**Issue by zachsai** [Tictim/Paraglider#28]
[stamina]
	#Paragliding and ascending will consume stamina.
	paraglidingConsumesStamina = false
	#Actions other than paragliding or ascending will consume stamina.
	runningAndSwimmingConsumesStamina = false

Is not working on servers. Works on single player but not servers. Both client and server have the same config.
(Stamina is being consumed when it is supposed to not be used when paragliding)
https://streamable.com/8ecn50

Here is a video of it not working while on my modpack server

**Comment by Tictim** [comment]
Your statement of "client and server having the same config" confuses me. The config option is located in server config, which is nonexistent in clients :P

Although I did find issue related to said configs, your issue seems to be nothing more than the modification simply not applied to server. It's impossible for me to know why, but I suspect it's likely due to mistakes on your end.

Try things below, and tell me again if it still malfunctions.
 * Make sure you modified correct config file, i.e. the config in your world file for your server.
 * If you made changes while the game is running, make sure the config is actually accepted. Sometimes the game completely ignores config changes.

**Comment by Tictim** [comment]
Closing this because there's no response.
