### ISSUE TITLE
[Suggestion] Cross-mod compatibility ideas

### ISSUE THREAD

**Issue by Neko2n** [Tictim/Paraglider#33]
It'd be awesome if we could get support for Elenai Dodge 2 where dodging consumes/requires stamina instead of the feather bar the mod ships.

Another mod that'd be nice to have cross-compatibility for would be Project MMO. Agility levels could increase stamina naturally alongside stamina vessels, or instead of stamina vessels if you decide to turn them off.

**Comment by Tictim** [comment]
I don't know either of these mods. But I am fairly certain that implementing the feature from my side, and tying this mod to other mods are bad. The proposal is deeply tied down to mod-specific features(dodging and... Agility?), and relying on implementation details seems inevitable. I have no interest in maintaining such fragile code for cross-mod feature. Maybe Project MMO thingies. But the proposal itself sounds somewhat dubious so eh.

The best thing you could do is telling them to add cross-mod features. But now you can't, since this mod doesn't even have API 😛. Making stamina attribute-based system and separating stamina interface capability seems good point to start. For now... You'd have to wait.
