### ISSUE TITLE
Bug with Hard Softcore Mod

### ISSUE THREAD

**Issue by ColaLiao** [Tictim/Paraglider#42]
Play with Hard Softcore Mod

1.Use Heart Containers of Paraglider Mod

2.Dead, lose 1 heart

3.Use Totem of Vitality of Hard Softcore Mod

 

after that, i got 10 heart...

**Comment by Tictim** [comment]
The Heart Container logic is completely isolated from another attributes and shouldn't be affected, unless the mod references this mod directly via code.

I suspect another mod is at play. Please contact me after verifying the bug is not originated from any other mod but this, and I will re-open the issue.
