### ISSUE TITLE
JEED Support

### ISSUE THREAD

**Issue by zachsai** [Tictim/Paraglider#47]
![image](https://user-images.githubusercontent.com/63996164/162332334-3a4af708-29bd-426d-9df8-7cb0c4984147.png)
Could you add an effect icon and description for support with JEED (just enough effect descriptions)

**Comment by Tictim** [comment]
There's no effect icon because it isn't displayed anywhere. The effect is only used internally (the game continuously applies it when you're out of stamina, and that's it), and never interacts with player as 'potion effect' or similar, so I don't see the merit of writing description as effect.

I'd rather just hide it from list, but no such feature is written in mod description, so...
