### ISSUE TITLE
[Feature request] So why not remote attack while paragliding?

### ISSUE THREAD

**Issue by xitieshiz2** [Tictim/Paraglider#51]
As the title, you can use your bow to enter bullet time and do a remote attack in BoTW, why not in this mod? There is something pretty similar to the 'bullet time', Steve's speed has a slowdown when he's using his bow.

**Comment by Tictim** [comment]
First of all - I don't think bullet time in BotW is more of an ability of Link than some kind of special maneuver that all users of Paraglider possess, but whatever.

Mechanism-wise, the bullet time in BotW isn't strictly tied to paragliding; They just activates whenever you draw a bow midair. And we can't just bluntly stick such intrusive mechanism in the game because the base game did so, which means a new specification better suited for Minecraft is needed (assuming it's being included in this mod). There's also a number of technical challenges here and there, but it isn't of an importance right now.

Lastly, although this mod has been kind of overblown from initial scope of "the funny hangglider thingy from your favorite game", transplanting every BotW feature into Minecraft has never been the scope of this mod and I don't plan to do it. The more I look at bullet time suggestions, the more I feel like "this should be a bow thing, not paraglider thing"; And I don't want to include feature that doesn't have strong connection with paraglider in mod named Paraglider.
