### ISSUE TITLE
[Feature Request] Paraglider Always Enabled

### ISSUE THREAD

**Issue by Dradon7** [Tictim/Paraglider#64]
How feasible is it to add a config option to always enable the paraglider functionality, even without holding the item? This would closer match BOTW gameplay: anytime while falling, you can press jump to deploy the paraglider. However, I know that when coding, seemingly simple small changes have a tendency to cause the most headaches and be more trouble than their worth.
If it needs to be an item for whatever reason, maybe there could be curios compatibility?

I'm just looking for a way to stop the paraglider from taking up a hotbar slot.

**Comment by Tictim** [comment]
Time to time there's suggestion about "hand-less paragliding" and I always find them very awkward. Why would you make an item so obviously used by hands, not require hands to operate? Following specifications about these new 'alternative paragliding' methods just exist to resolve the disparity of not-using-hands-but-kind-of-using-hands nature of the method themselves, which content-wise I find it unappealing and in concept-wise I disagree with.

For implementation side, a lot of the code assume that Paraglider is a thing you hold in your hand. Especially on client side, which rendering is just done with vanilla item models and the only part solely controlled by mod-added code is raising arms of paragliding players. Changing these would mean major rewrite; including both on server side and client side. Though, it is possible. Should be. I don't know. Some dude DM'd me asking about how did I render Paraglider and they said they were making Curios support for Paraglider for private use. Never heard anything back, so I'd say it's an open-ended question.

I will close this issue because I don't find the idea that compelling. Feel free to leave comment if you have something to add on.
