### ISSUE TITLE
How do I remove the effects of goddess statues?

### ISSUE THREAD

**Issue by JunkieZemian** [Tictim/Paraglider#70]
me and a friend of mine started a server in creative to make an initial house but then we continued in survival, only he has a lot of stamina, and I wanted to know if it was given by the effect of a goddes statue that he got in creative. how do i get the effect?

**Comment by Tictim** [comment]
Do you want to remove the Stamina Vessels, or get the vessels, or just know whether the vessel that the guy have came from Goddess Statue? I guess I will just answer all three of them.

To get the Stamina Vessels in "unmodified" version of the mod, you need to either:
 * Collect 4 Spirit Orbs from various chests/spawners and exchange with Stamina Vessels; or
 * Kill one of the bosses(either Ender Dragon or Wither) which drops Heart Container. Then bargain with Horned Statue to convert it to Stamina Vessel. This exchange incurs 1 emerald fee. If Heart Container is disabled in the common config, killing bosses directly drops Stamina Vessel.
 * Or use save editor I guess.

To remove the Stamina Vessels in the mod, you need to either:
 * Sell your vessels to Horned Statue; or
 * Use Anti-Vessel - a creative mode only item that retrieves all your Heart Containers and Stamina Vessels consumed into items.
 * Or use save editor I guess.

Commands for querying/modifying Heart Containers and Stamina Vessels are planned, but not implemented.

It is impossible to know about the exact origin of a vessel, although you can find subtle information hinting when they got their first vessel from server log.
 * Exchanging Spirit Orbs with Goddess Statue gives you 'Pray to the Goddess' Advancement.
 * Performing any bargain with Horned Statue gives you 'Statue's Bargain' Advancement.
 * Maxing out all heart and stamina gives you 'Hero of Hyrule' advancement.

All three of these advancements are displayed in the chat, so it can be somewhat viable information for figuring out whether the man in question spawned the stamina vessel item or not; though this information will be useless if they had bargained prior to cheating, or spawned Spirit Orbs instead of hearts or vessels.

Hope this information helps. If you have further questions, post it below.
