### ISSUE TITLE
Change location of stamina wheel

### ISSUE THREAD

**Issue by Cobyt3** [Tictim/Paraglider#74]
Hello, I was wondering if it's possible to change the location of the stamina icon/ wheel. Specifically, I want it to be in the middle above the hotbar XP Levels. Thank you!

**Comment by Cobyt3** [comment]
Just found https://github.com/Tictim/Paraglider/issues/37

Sorry for opening another issue

**Comment by Orangejewce92** [comment]
any update on this? i would also like it moved

**Comment by Cobyt3** [comment]
> any update on this? i would also like it moved

Press CTRL + P ingame. It will open a menu where you can freely move it around

**Comment by Orangejewce92** [comment]
Conflicting mod issues. I have PMMO installed control P opens a gui for this other mod. With no configuration. So I haven't been able to check. - the plan was to check with only paraglides installed but I haven't been to my computer since. 
- I haven't looked but is this option available to be changed in controls?

**Comment by Cobyt3** [comment]
> Conflicting mod issues. I have PMMO installed control P opens a gui for this other mod. With no configuration. So I haven't been able to check. - the plan was to check with only paraglides installed but I haven't been to my computer since. 
> - I haven't looked but is this option available to be changed in controls?

I think so yes
