### ISSUE TITLE
Suggestion/enhancement: Make Stamina an API which other mods can use for their own systems. 

### ISSUE THREAD

**Issue by Darkmega18** [Tictim/Paraglider#77]
similar to feathers by elenai used for elenai dodge, would you be able to make your stamina system into an extendible AI that other people can use?
The maker of parcool actually said they would support such a development if it existed in my own suggestion to them (second link).

https://github.com/alRex-U/ParCool/issues/137
https://github.com/alRex-U/ParCool/issues/164

**Comment by Silvertide7** [comment]
I massively second this. I created a branch of Parcool and made it compatible with this mod, but it only updates the client side of the PlayerMovement Cap. It looks like it's working on the client but I don't think it's actually taking stamina away from the player server side, so you never actually run out of or spend stamina. It seems to be because of the way PlayerState is hardcoded into all of the PlayerMovement update methods. Either that or I need to send a packet to update the server of what is happening on the client.

**Comment by Tictim** [comment]
Starting from 20.1.0 Paragliders now offers API for modifying movement/stamina system.

And yes, movement in this mod are tracked and evaluated on server side. The evaluated state is then synced to clients. So just modifying states on client side would only create desync.

**Comment by Darkmega18** [comment]
yes-yes-yes! :D
