### ISSUE TITLE
Swimming Suggestion

### ISSUE THREAD

**Issue by Aabaddon** [Tictim/Paraglider#89]
Is it possible to make that if you lose all your stamina you cant float anymore?... like if youre swimming and the stamina reaches zero you straight up sink, this would help making boats more usefull

**Comment by Tictim** [comment]
I didn't want to make such thing, because you have to either create "reset player position to shore" system, which is hard. or just let players drown, punishing them for swimming in the pool for too long.

Also, additional modifications to movement systems are the kind of thing I'm trying to avoid; other people can make addons that implement the system, but I have no intention to implement it in the base mod.
